"""empty message

Revision ID: 38c47f708a0
Revises: 33d0af947fd8
Create Date: 2015-02-05 16:36:00.125668

"""

# revision identifiers, used by Alembic.
revision = '38c47f708a0'
down_revision = '33d0af947fd8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
